services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgess-db-pp1-database_systems'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '32830:5432'
